zeromq/zmq.rs

src/consts.rs
src/msg.rs
src/result.rs
src/socket_base.rs
src/stream_engine.rs
src/tcp_connecter.rs
src/tcp_listener.rs
src/v2_decoder.rs
src/v2_encoder.rs

These are just a few quick refactors to keep pace with changes in the rust language.
* Updated attribute `deriving` -> `derive`
* Refactored `std::io` -> `std::old_io`
I was unable to solve some failures surrounding the `SocketAddr::from_str` function.  For some reason it is not recognized.  So this doesn't bring `zmq.rs` to build-ready, but hopefully it takes care of some of the busy-work.

Update with language changes

---

.github/workflows/main-ci.yml
.travis.yml
rustfmt.toml

This switches from travis CI to github actions.
Added:
- main-ci.yml, which describes the main CI workflow of the project. Deployment CI will likely go in a separate workflow.
- Four CI jobs: check that code compiles, check that tests pass, check that code is formatted, check for lints. The lint job can fail and will produce warnings instead of blocking a merge.
- Added a rustfmt.toml file. While technically unnecessary, it announces that the project is formatted with rustfmt and any deviations from the default config.
Removed:
- travis config yaml
The following in the repo settings will require the status checks to pass before merging to master:
1. Go to settings, branches, then add rule.
2. Enter the name of the branch as `master`
3. Select "Require status checks to pass before …

Added github-actions CI and removed travis

---

src/lib.rs

I've added a prelude module, akin to the standard library's prelude module and similar modules in other crates. The intent is that we can put commonly used traits here to help people more easily use the library - they won't get errors about missing functions if they `use zeromq::prelude::*`.

Added prelude module

---

src/lib.rs
tests/pub_sub.rs
tests/rep_req.rs

Currently rebased on #61, see that one first
I moved the contents of `zeromq::tests` into cargo's `tests` directory, to better align with cargo's package layout, as well as re-frame the tests as integration tests. This ensures the tests only depend on externally visible functionality. I've also organized them by socket type, so its a little more modular and helps make clear what is and isn't tested.

Integration tests

---

tests/pub_sub.rs

Currently rebased on #62, see that one first
I refactored the pub_sub test to allow for multiple addresses to be tested, and am now testing multiple ipv4 and ipv6 addresses.
I also took the opportunity to make the test less flaky - there is no guarantee that the current time of receipt matches when it was sent, and this caused the test to fail non-deterministically. I fixed it by cloning the payload so that the received value could be directly compared against the expected value in the subscribers.

Fix flaky test and test multiple addresses

---

.github/workflows/main-ci.yml
src/lib.rs

Rebased on #67, see that PR first
denying warnings in the crate itself rather than in only CI has a few harmful effects, which include accidentally making what would otherwise be backwards compatible changes into breaking ones. For example if a dependent crate marks some functionality as deprecated or a new warning is added to the rust compiler, these are considered minor version changes, but would be breaking if we deny all warnings.
In this PR I have stopped denying warnings. To achieve the same effect as what was originally intended I have made passing the linting step of CI required and the linter now denies warnings. This should keep the intended effect (we don't tolerate warnings), but avoid the unintended consequence of violating semver compatibility.
See also:
- …

No longer #![deny(warnings)]

---

Cargo.toml
examples/message_broker.rs
examples/message_client.rs
examples/socket_client.rs
examples/socket_server.rs
examples/weather_client.rs
examples/weather_server.rs
src/dealer_router.rs
src/endpoint.rs
src/error.rs
src/lib.rs
src/pub.rs
src/rep.rs
src/req.rs
src/sub.rs
src/util.rs
tests/pub_sub.rs
tests/rep_req.rs

I've added an `Endpoint` enum, along with a `Host` and `Transport` enum. These enums should help us add support for new transport types other than tcp or udp.
Without the enums, I found myself having to check the syntax of the string based endpoint a lot. For example, if its tcp the string should be host:port, but if its ipc it should just be a string address. By consolidating all of these checks into the parse() method of `Endpoint`, we can avoid scattering these parsing and checking steps everywhere in the code, and we can also let people avoid that overhead by directly constructing the Endpoint.
```rust
let str_endpoint: Endpoint = "tcp://example.com:4567".parse()
let enum_endpoint = Endpoint::Tcp("example.com".to_string(), 4567)
```
Things to discuss:
1. I have not figured out the …

Added Endpoint enum to better encode endpoints for different transport types

---

src/dealer_router.rs
src/endpoint.rs
src/lib.rs
src/pub.rs
src/rep.rs
src/req.rs
src/sub.rs
src/util.rs
tests/pub_sub.rs

Zeromq lets you bind to the unspecified ipv4 interface or the unspecified ipv6 interface. It also lets you bind to any available port via port 0. This PR adds the necessary logic for these cases, as well as unit tests for the functionality in `Pub` ports, along with the `Socket::binds()` function which returns a list of the resolved endpoints.
Side note: A lot of these tests are brittle to maintain, because we have to hard code the port numbers that won't clash with any other running processes, or any of the other ports in the unit/integration tests. Its probably a good idea to make a utility for tests to get port numbers that won't conflict with the other tests, but thats out of scope for this PR

Allow endpoints with port 0 or unspecified interface

---

.github/workflows/main-ci.yml
src/codec.rs
tests/pub_sub.rs

Clippy and check were not running on tests. Additionally, all of the commands only ran on the particular package, rather than all packages (only relevant in the presence of multiple workspaces, of course). This PR addresses these issues.

Ci check and lint tests as well as workspaces

---

src/endpoint/host.rs
src/endpoint/mod.rs
src/endpoint/transport.rs
src/pub.rs
src/sub.rs
src/util.rs
tests/pub_sub.rs

I'm trying to break up #72 to be a bit smaller, so I've manually extracted some of the changes from there to this separate PR.
This PR reorganizes the endpoint module to break it up into a few submodules. This helps readability and makes it easier to navigate that code.
I've also fixed some issues with how endpoints and hosts displayed and parsed IPV6 addresses. I've reworked the semantics of `Host::Ipv6` to more closely match the semantics of `std::net::Ipv6Addr`, and added associated tests. This removes the need for the `format!("{}:{}", host, port)` that I was doing whenever I passed a host and port tuple to tokio, and correspondingly fixes the bugs in the parts of the code that weren't using that.
I also fixed a flaky test - as mentioned in #73, our sockets are not yet resistant to …

Reorg endpoint, fix flaky test, fix `Host` Ipv6 parse and display

---

Cargo.toml
benches/req_rep.rs
src/codec.rs
src/dealer_router.rs
src/lib.rs
src/util.rs

This MR is a smaller change than #77, which avoids any dynamic dispatch or boxing. It is intended to isolate the changes to just that what is necessary to use `futures_codec` and `tokio_util::compat` instead of `tokio_util::codec`. 
~**Don't merge this MR** - we need to merge some basic performance benchmarks to master first,~ and then we can see the performance impact of the codec changes, separately from the dynamic dispatch stuff in #77.

Ported code to use futures_codec and tokio_util's Compat

---

src/dealer_router.rs
src/endpoint/mod.rs
src/lib.rs
src/pub.rs
src/rep.rs
src/req.rs
src/sub.rs
src/transport/mod.rs
src/transport/tcp/mod.rs
src/transport/tcp/tokio.rs
src/util.rs

~Rebased on #77 - I suggest diffing against that for review~
In preparation for new transport types, this PR takes steps to generalize the signatures of `transport::connect()` and `transport::begin_accept()`. This should help make it trivial to add support for new transports to pubsub and reqrep. It also wraps the oneshot channel for killing the accept task in a struct to increase type safety.

Further generalize across transports

---

tests/pub_sub.rs
tests/rep_req.rs

The tests can easily collide on ports. Refactored to use port 0 select any free port instead.

Tests now use 0 port where possible to avoid collisions

---

Cargo.toml
src/endpoint/mod.rs
src/endpoint/transport.rs
src/transport/ipc/mod.rs
src/transport/ipc/tokio.rs
src/transport/mod.rs
src/transport/tcp/tokio.rs
src/util.rs
tests/pub_sub.rs
tests/rep_req.rs

~Rebased on #83, might want to diff against that for review.~
First alternative transport type! This PR implements the IPC transport with unix sockets. Because the underlying IO was abstracted out in #77, this was fairly straightforward and required only adding in the necessary ipc module in `transport`, as well as a representation for the IPC endpoint.

IPC Implementation!

---

benches/pub_sub.rs
benches/req_rep.rs
src/endpoint/host.rs
src/transport/ipc/tokio.rs
src/transport/tcp/tokio.rs

Adds ipc to the benchmarks for each socket type, and groups them against the other transports for comparison

Added ipc benchmark

---

src/dealer_router.rs
src/error.rs
src/lib.rs
src/pub.rs
src/rep.rs
src/req.rs
src/sub.rs
tests/pub_sub.rs
tests/rep_req.rs

Currently rebased on #88 
Fixes #87 by giving users the ability to `close()` sockets, which will block until the socket is destroyed. Updates the tests to use this feature.

Fix racey unbind in tests, and add Socket.close() and Socket.unbind()

---

src/codec/greeting.rs
src/codec/mod.rs
src/error.rs
src/util.rs

One of the compliance tests was failing for me locally, because the peer was using a newer version of the ZMTP protocol.
According to the spec, instead of checking for a specific version supported by this implementation, we should allow any version that is equal or greater, as in this case the peer should adjust to us. If they choose not to, they are expected to close the connection immediately.
Similarly, this implementation may support communication with peers using the older version of the ZMTP protocol in the future.

Relax ZMTP version requirements according to the spec

---

.github/workflows/main-ci.yml

Currently, CI will run for any pushes on `zeromq/zmq.rs`, but not on pull requests. This works fine for any maintainers of the repo, but contributors with their own forks will not have any CI run for their pull requests. This is because their pull request does not ever `push` to the repo, until after the merge request is approved and merged. This means that untested code via PRs submitted from forked repos can merge to master. You can observe this behavior in #106 for example: At the time of writing, that PR failed CI on my forked repo, but no CI was run on the main repo.
To avoid this, I believe the correct course of action is to have the workflow trigger on pull request, rather than on push. This will solve the fork issue, and @Alexei-Kornienko already opens PRs for everything anyway, …

Fixed CI not running for PRs

---

Cargo.toml

We mentioned this a few months ago in a PR that the recommended way to specify semver dependencies in Cargo is by omitting the "^" symbol, as its implied. Here's the original thread: https://github.com/zeromq/zmq.rs/pull/88#discussion_r507217746
I've taken the liberty and made the Cargo.toml file consistent with this style, lmk if this cosmetic change is amenable to you!

Updated Cargo.toml to consistently use the canonical semver syntax

---

src/async_rt/mod.rs
src/async_rt/task/mod.rs
src/async_rt/task/tokio.rs
src/codec/framed.rs
src/codec/mod.rs
src/lib.rs
src/pub.rs
src/task_handle.rs
src/transport/ipc/tokio.rs
src/transport/tcp/tokio.rs

In preparation for #108, this PR refactors the last few places where we bake tokio-specifc functionality into the code, and organizes them into the `async_rt` module. The `async_rt` module will serve as a common denominator between the different runtimes we wish to support, and bundle up any runtime-specific code that we can't accomplish simply with just `futures`.
The main parts of this are providing a way to spawn and join on tasks in a runtime agnostic way, as well as a minor refactor of a couple things that could be done with `futures` instead of `tokio`

Refactor last few tokio specific parts to be runtime agnostic

---

.github/workflows/main-ci.yml
Cargo.toml
README.md
src/codec/framed.rs
src/endpoint/error.rs
src/task_handle.rs
src/transport/mod.rs

Not all platforms will support all transport types. For example, only linux supports ipc, and wasm won't support either ipc or tcp. In preparation for a more robust way of handling platform specific transports, I've gone ahead and feature gated each transport type.
You will notice that I did not feature gate the actual variants of an `Endpoint`. This is because the public API should not change just because we add or remove a transport feature. Additionally, we likely still want the ability to describe endpoints of various types, regardless of if we actually support interacting with them for a given set of features.

Feature-gate each transport type

---

src/lib.rs
src/transport/ipc.rs
src/transport/mod.rs
src/transport/tcp.rs
src/util.rs

This enables us to connect socket to server that doesn't exist yet.

Implement connect_forever in util. Related to #73

---

examples/message_broker.rs
examples/message_client.rs
examples/socket_client.rs
examples/socket_server.rs
examples/stock_client.rs
examples/stock_server.rs
examples/task_ventilator.rs
examples/weather_client.rs
examples/weather_server.rs
src/backend.rs
src/codec/mod.rs
src/codec/zmq_codec.rs
src/dealer.rs
src/message.rs
src/pub.rs
src/rep.rs
src/req.rs
src/router.rs
src/sub.rs
src/util.rs
tests/pub_sub.rs
tests/pub_sub_compliant.rs
tests/req_rep.rs
tests/req_rep_compliant.rs

The specification says all messages can contain multiple frames.  This
commit gets rid of the distinction between multipart and non multipart
messages.  It does this by having all user facing methods take and
return ZmqMessage structures.  I also modified that structure to be a
wrapper around a VecDeque of Bytes.
Fixes #119

Make all socket types support multipart messages.

---

examples/socket_client_with_options.rs
src/backend.rs
src/codec/command.rs
src/dealer.rs
src/lib.rs
src/pub.rs
src/pull.rs
src/push.rs
src/rep.rs
src/req.rs
src/router.rs
src/sub.rs
src/util.rs

This is related to #116.
Currently it's only enables user to set custom peer-identity if needed
and passes options all around. Later we can add other options to this
struct.
Some minor changes to ReadyCommand properties were required cause
ZMQ_IDENTITY could be any byte vec and not guaranteed to be valid String

Added basic SocketOptions struct

---

Cargo.toml
src/codec/framed.rs
src/codec/zmq_codec.rs
src/lib.rs
src/util.rs

The author of `futures_codec` appears to be [awol](https://github.com/matthunz/futures-codec/pull/57), blocking downstream crates from updating to bytes="1", so the repo has been forked and republished as [asynchronous-codec](https://crates.io/crates/asynchronous-codec)
This PR updates `Cargo.toml` and substitutes `futures_codec` for `asynchronous_codec` in src files

Updated dependencies (in particular bytes="1")

---

src/message.rs
src/rep.rs
tests/message.rs

Using split_off instead of split_at in ZmqMessage.

---

examples/forwarder_device.rs
src/backend.rs
src/lib.rs
src/pub.rs
src/rep.rs
src/req.rs
src/sub.rs
src/util.rs

In order to provide functionality required by following example #147 a patch to PUB and SUB sockets should be implemented.
Quote from dev on discord:
```
subscriber socket should keep list of his subscriptions and send it to PUB socket when it connects
```
**Todos**
Any comments regarding possible solutions are appreciated.
Thanks.

feat: add support for reverse binding between PUB and SUB

---

src/backend.rs
src/fair_queue.rs
src/pull.rs
src/router.rs
src/sub.rs

ConnectionReset is a common error that occurs here.
Invoking peer_disconnected regardless of the error might be a little coarse but that should be better than raising a panic.

Handle errors in Pull and Router

---

examples/socket_client_with_options.rs
src/error.rs
src/lib.rs
src/router.rs
src/util.rs

This makes cloning of PeerIdentity (which is performed quite often) much cheaper.
Also adds a `from_slice` method and a `FromStr` implementation.

Use Bytes inside PeerIdentity

---

Cargo.toml
src/endpoint/mod.rs

`once_cell` is better maintained, avoids macros, and is already in the dependency tree.

Switch lazy_static to once_cell

---

Cargo.toml
src/lib.rs
src/util.rs

- Remove `enum-primitive-derive` and `num-traits` dependencies
- Move `sockets_compatible` to a method
- Add `FromStr` implementation and support parsing from bytes

SocketType cleanups

---

Cargo.toml
src/codec/mechanism.rs

Deriving Default for enums was stabilized in 1.62.0.

Automatically derive a Default impl

---

Cargo.toml

This almost halves the time required to compile regex.

Only use required features of regex crate

---

src/async_rt/task/mod.rs

This allows separate calls to `spawn` to show separately in tokio-console, rather than having it show all tasks as originating from the `spawn` function itself.

Track caller when spawning async tasks

---

src/req.rs

Hey there. 
This PR handles codec errors when reading from a REQ socket and thus makes the code more resilient to abrupt changes in the underlying tcp connection. In my experience, it was relatively easy to make the panic happen during tests.
Not sure what's planned for the ` Some(Ok(_))` arm, so I've left it as `todo()`.
Hope this helps. Please let me know if I should do anything particular with the PR. Cheers!

Handle codec errors in REQ socket recv

---

src/transport/mod.rs

Hey all! I'm hoping to get a zeromq backed Tauri app to build on all systems. See https://github.com/nteract/nteract-next/pull/16 for the app and the current PR.
I've added in a check for both the `ipc-transport` feature flag and checking that the platform is a *nix system. Let me know if there's a better approach for this.

only build ipc transport on *nix systems

---

.github/workflows/main-ci.yml
Cargo.toml
benches/req_rep.rs
examples/async_helpers/mod.rs
src/async_rt/mod.rs
src/async_rt/task/join_handle.rs
src/async_rt/task/mod.rs
src/transport/ipc.rs
src/transport/mod.rs
src/transport/tcp.rs

[`async-dispatcher`](https://github.com/zed-industries/async-dispatcher) allows us to use ZeroMQ with native schedulers instead of relying directly on Tokio or async-std's `spawn`.
As for why, [Zed uses native OS schedulers for async work](https://zed.dev/blog/zed-decoded-async-rust).

Introduce async-dispatcher runtime feature

---

src/fair_queue.rs

As described [in the changelog](https://github.com/rust-lang/futures-rs/blob/master/CHANGELOG.md#0331---2024-10-05) and [here](https://github.com/rust-lang/futures-rs/pull/2830) with the latest version of futures-task they update the function `waker_ref` making it 'static. For this, zmq needs also to add 'static to some properties.

Added support for futures-task v0.3.31

---

Cargo.toml
examples/task_worker.rs
src/backend.rs
src/codec/framed.rs
src/codec/mod.rs
src/dealer.rs
src/error.rs
src/fair_queue.rs
src/lib.rs
src/pub.rs
src/pull.rs
src/push.rs
src/rep.rs
src/req.rs
src/router.rs
src/sub.rs
src/task_handle.rs
src/transport/ipc.rs
src/transport/mod.rs
src/transport/tcp.rs
src/util.rs
tests/pub_sub.rs
tests/req_rep.rs
tests/req_router_dealer_rep.rs

I'm working on implementing `Stream` and `Sink` for the `RouterSocket` and `DealerSocket` again so that we can implement `.split()` and I wanted to make sure these types were aligned for downstream packages.

migrate to using plain `futures` crate

---

src/lib.rs

De-nest more `match ZmqResult` segments with use of the `?` operator.

Simplify match and error

---

src/dealer.rs
src/lib.rs
src/pull.rs
src/rep.rs
src/req.rs
src/router.rs
src/sub.rs

Drops `todo!()` from `dealer.rs` and propagates errors from proxied sockets.

handle errors from the fair queue and the case when the queue is empty

---

src/fair_queue.rs

The fair queue iterator implementation returns `Poll::Pending` when there may be other streams in the priority queue that are ready. Instead of returning after checking only the top stream, continue checking until a stream that returns `Poll::Ready` is found, or all streams have returned `Poll::Pending` and will resubmit themselves to the priority queue when they are ready. 
I had an issue that can be summarized as the following: I had a server with a pull socket, and two clients connecting with push sockets. One client was fast and sent a message every second. The other client was slow and sent a message every 5 seconds. I expected the server to receiver 5 messages from the fast client, and then a single message from the slow client, and that this would repeat. I observed the eventually, …

Continue polling clients in priority queue if the top is not ready

---

src/fair_queue.rs

This is to add two tests to #208 and `fair_queue` which fixes the case when one client's `Pending`  causes fair queue not fair when other streams are not ready yet.

Test fair queue continues to be polled if a stream returns Pending

---

examples/task_ventilator.rs
src/dealer.rs
src/fair_queue.rs
src/lib.rs
src/pull.rs
src/rep.rs
src/req.rs
src/router.rs
src/sub.rs
src/util.rs

Fix a few lint errors: needless continues and iterating maps.

Remove needless continues and fix lint errors
