zeromq/zmq.rs

src/dealer_router.rs
src/lib.rs
src/pub_sub.rs
src/util.rs

This will allow to reuse common code parts in all sockets

Move custom socket code into trait impl

---

Cargo.toml
examples/socket_server.rs
src/req_rep.rs
src/tests.rs

Now this socket seems to be spec compliant. Need to test it properly and benchmark overall code

Implemented round robin and other spec related features for ReqSocket

---

.github/workflows/main-ci.yml

The github actions are not running on pull requests. This is a mistake on my part, which I've fixed in this PR

Fixed workflow not running on PR

---

Cargo.toml
src/dealer_router.rs
src/endpoint/error.rs
src/endpoint/mod.rs
src/error.rs
src/lib.rs
src/pub.rs
src/rep.rs
src/req.rs
src/sub.rs
src/task_handle.rs
src/transport/ipc/mod.rs
src/transport/ipc/tokio.rs
src/transport/mod.rs
src/transport/tcp/mod.rs
src/transport/tcp/tokio.rs

Adds a few primitives that should make it easier to work with tasks going forward. Also refactors the code to use this for the accept handle.
Does not yet address #87

Improved error msgs, added TaskHandle, TaskError, AcceptStopHandle

---

Cargo.toml
examples/weather_server.rs
src/transport/ipc/tokio.rs
src/transport/tcp/tokio.rs
tests/pub_sub.rs
tests/pub_sub_compliant.rs
tests/req_rep.rs

Rebased on #107 due to CI not running

Update to Tokio 1.0, Fix racey test

---

src/codec/zmq_codec.rs

Use ZmqMessage instead of just Vec<Bytes>. This removes the need in
extra conversions and improves error handling a little bit.

Minor refactoring of codec code.

---

src/message.rs
src/pub.rs
src/rep.rs
src/req.rs
src/router.rs

These asserts ensure that data that we pass around is valid

Added some more asserts.

---

examples/message_client.rs
examples/socket_client.rs
examples/stock_client.rs
examples/task_sink.rs
examples/task_ventilator.rs
examples/weather_client.rs
src/lib.rs
src/pub.rs
src/pull.rs
src/push.rs
src/rep.rs
src/req.rs
src/sub.rs

Removed separate NonBlocking trait. Rename base traits.

---

README.md

Clarify async-std usage

---

examples/message_broker.rs
src/dealer.rs
src/lib.rs
src/pub.rs
src/push.rs

Added prototype of proxy function.

---

src/transport/tcp.rs

I think these additional lines in `transport/tcp.rs` are all that's required.

Disable Nagle on all sockets

---

examples/message_server.rs
src/async_rt/task/mod.rs
src/message.rs
src/rep.rs
tests/helpers.rs
tests/message.rs
tests/req_rep.rs
tests/req_router_dealer_rep.rs

Fixed Rep socket panic when message comes from Dealer.

---

src/pub.rs

Error will occurred if topic have different length ,so compare length first.

length of topics are different

---

src/backend.rs

Refactored send_round_robin

---

src/codec/zmq_codec.rs

Fix build check error

---

Cargo.toml
tests/compliance/mod.rs
tests/pub_sub_compliant.rs
tests/req_rep_compliant.rs

now ,zmq are not update ,replaced by zmq2,  zmq2 <- zmq-sys2 <- libzmq-src, now v4.3.4

change  zmq into zmq2

---

Cargo.toml
src/backend.rs
src/req.rs
src/sub.rs

This simply reduces the dependencies.

Use crossbeam-queue instead of parent crossbeam crate

---

README.md

Include new runtime support in README.

update readme with status and runtime support

---

Cargo.toml

Update the crate metadata to list the top committers/maintainers.

update author metadata

---

.github/workflows/main-ci.yml

Bump to actions/cache@v4
